name: Build Fabulist

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.lua == '5.1' }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        configuration: [ RelWithDebInfo, MinSizeRel ]
        lua: [ "5.1", "5.2", "5.3", "5.4" ]

    steps:
    - uses: actions/checkout@v2

    - uses: novelrt/setup-cpp@v1

    - name: Generate build system
      shell: bash
      run: |
        cmake \
          -DCMAKE_BUILD_TYPE="${{ matrix.configuration }}" \
          -DCMAKE_INSTALL_PREFIX=inst \
          -DFABULIST_LUA_VERSION="${{ matrix.lua }}" \
          -DFABULIST_ALL_ON=ON \
          -Wdev -Wdeprecated -Werror=dev -Werror=deprecated -S . -B build

    - name: Build Fabulist
      run: cmake --build build --parallel --config ${{ matrix.configuration }} --verbose

    - name: Generate artifact
      run: cmake --install build --config ${{ matrix.configuration }} --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fabulist-${{ matrix.os }}-${{ matrix.configuration }}-lua${{ matrix.lua }}
        path: inst

  merge-artifacts:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        lua: [ "5.1", "5.2", "5.3", "5.4" ]

    steps:
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Merge build artifacts
      run: |
        mkdir merged
        for artifact in $(find ./artifacts/ -type d -name "fabulist-${{ matrix.os }}-*-lua${{ matrix.lua }}"); do
            cp -RT "$artifact" merged/
        done
    - name: Upload merged artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fabulist-${{ matrix.os }}-lua${{ matrix.lua }}
        path: merged
