name: Build Fabulist

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        configuration: [ RelWithDebInfo, MinSizeRel ]

    steps:
    - uses: actions/checkout@v2

    - name: Generate build system
      run: cmake -DCMAKE_BUILD_TYPE="${{ matrix.configuration }}" -DCMAKE_INSTALL_PREFIX=inst -S . -B build

    - name: Build Fabulist
      run: cmake --build build --parallel --config ${{ matrix.configuration }}

    - name: Generate artifact
      run: cmake --install build --config ${{ matrix.configuration }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fabulist
        path: inst
