name: Pull Request validation

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - uses: novelrt/setup-cpp@v1

    - name: Generate build system
      shell: bash
      run: |
        cmake \
          -DCMAKE_INSTALL_PREFIX=inst \
          -DFABULIST_THIRDPARTY=ON \
            -DFABULIST_THIRDPARTY_LUA=ON \
            -DFABULIST_THIRDPARTY_SOL=ON \
          -DFABULIST_COMPILER=ON \
            -DFABULIST_COMPILER_CLI=ON \
          -DFABULIST_RUNTIME=ON \
          -DFABULIST_SAMPLES=ON \
            -DFABULIST_SAMPLE_CLI=ON \
          -Wdev -Wdeprecated -Werror=dev -Werror=deprecated -S . -B build

    - name: Build Fabulist
      run: cmake --build build --parallel --verbose

    - name: Generate artifact
      run: cmake --install build --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fabulist-pr-${{ matrix.os }}
        path: inst
